import numpy as np
from app.rag.lancedb_client import lancedb_client

# Layer 1: Deterministic Denylist
DENYLIST_KEYWORDS = [
    "code", "programming", "javascript", "python", "css", "html", "react", "c++", "rust",
    "finance", "stock", "portfolio", "trading", "investment", "bitcoin",
    "sports", "football", "basketball", "cricket", "soccer", "olympics",
    "movie", "song", "actor", "hollywood", "celebrity", "entertainment",
    "politics", "election", "president", "democrat", "republican",
    "business strategy", "marketing plan", "startup idea",
    "travel", "hotel", "flight", "tourism", "vacation",
    "gaming", "xbox", "playstation", "nintendo", "minecraft",
    "creative writing", "write a poem", "write a story",
    "hack", "phishing", "bypass", "exploit"
]

# Explicit Domain Keywords for boosting classification
MEDICAL_KEYWORDS = [
    "days",
    "cocaine",
    "time",
    "also",
    "take",
    "like",
    "blood",
    "long",
    "problem",
    "pain",
    "back",
    "years",
    "pill",
    "treatment",
    "used",
    "pregnancy",
    "periods",
    "taking",
    "suggest",
    "months",
    "emergency",
    "weeks",
    "last",
    "information",
    "need",
    "three",
    "cause",
    "contraceptive",
    "side",
    "normal",
    "week",
    "drugs",
    "symptoms",
    "first",
    "done",
    "having",
    "through",
    "period",
    "body",
    "test",
    "much",
    "well",
    "four",
    "during",
    "water",
    "detected",
    "avoid",
    "taken",
    "yasmin",
    "effect",
    "hours",
    "better",
    "even",
    "year",
    "infection",
    "fine",
    "high",
    "anxiety",
    "disease",
    "effects",
    "penis",
    "still",
    "right",
    "cysts",
    "husband",
    "along",
    "tablet",
    "possible",
    "sperm",
    "causes",
    "feel",
    "powder",
    "small",
    "patient",
    "tablets",
    "medicine",
    "case",
    "good",
    "baby",
    "pcod",
    "start",
    "tests",
    "dose",
    "daily",
    "advice",
    "drops",
    "food",
    "medicines",
    "urine",
    "heart",
    "wait",
    "hour",
    "gynecologist",
    "alcohol",
    "gone",
    "weight",
    "size",
    "same",
    "want",
    "while",
    "less",
    "best",
    "understand",
    "times",
    "many",
    "continue",
    "kindly",
    "hope",
    "surgery",
    "obstetrician",
    "usually",
    "past",
    "system",
    "half",
    "removed",
    "menses",
    "drug",
    "every",
    "depression",
    "gynaecologist",
    "proper",
    "since",
    "trying",
    "skin",
    "into",
    "lead",
    "month",
    "reports",
    "pills",
    "history",
    "left",
    "morning",
    "over",
    "kalachikai",
    "once",
    "phenol",
    "read",
    "contact",
    "give",
    "think",
    "levels",
    "worry",
    "condition",
    "going",
    "friend",
    "suffering",
    "bleeding",
    "keep",
    "sometimes",
    "stress",
    "started",
    "specialist",
    "regular",
    "protect",
    "uterus",
    "completely",
    "pregnant",
    "control",
    "comes",
    "twice",
    "attachment",
    "term",
    "evaluation",
    "health",
    "identity",
    "advise",
    "early",
    "sleep",
    "night",
    "short",
    "follow",
    "tooth",
    "negative",
    "medication",
    "under",
    "cancer",
    "fluid",
    "another",
    "physical",
    "went",
    "increase",
    "combination",
    "single",
    "reason",
    "care",
    "life",
    "abdomen",
    "erection",
    "area",
    "reduce",
    "studies",
    "scan",
    "explain",
    "dosage",
    "multiple",
    "level",
    "delay",
    "number",
    "itself",
    "method",
    "delayed",
    "teeth",
    "five",
    "inner",
    "getting",
    "general",
    "within",
    "minutes",
    "hormones",
    "healthy",
    "were",
    "suggested",
    "brain",
    "diet",
    "family",
    "overcome",
    "people",
    "lining",
    "might",
    "around",
    "hypertension",
    "report",
    "tissues",
    "chronic",
    "female",
    "couple",
    "mother",
    "effective",
    "rule",
    "prescribed",
    "being",
    "inside",
    "hair",
    "without",
    "pressure",
    "safely",
    "serum",
    "root",
    "vomited",
    "extended",
    "using",
    "effectiveness",
    "severe",
    "chest",
    "cocktail",
    "little",
    "seen",
    "male",
    "things",
    "cannot",
    "nerve",
    "live",
    "feeling",
    "next",
    "issue",
    "however",
    "hormonal",
    "required",
    "soon",
    "milk",
    "worried",
    "fever",
    "down",
    "ovarian",
    "poop",
    "lower",
    "problems",
    "clear",
    "until",
    "birth",
    "really",
    "said",
    "second",
    "make",
    "attached",
    "child",
    "beta",
    "opinion",
    "available",
    "concern",
    "cholesterol",
    "whether",
    "masturbation",
    "discuss",
    "smoking",
    "work",
    "psychiatrist",
    "unprotected",
    "chance",
    "exercise",
    "stop",
    "ejaculate",
    "medications",
    "helps",
    "wrong",
    "ovulation",
    "fall",
    "vomiting",
    "feels",
    "bone"
]

LEGAL_KEYWORDS = [
    "primary",
    "upper",
    "schools",
    "secondary",
    "enrolment",
    "teachers",
    "category",
    "school",
    "class",
    "grade",
    "girls",
    "pradesh",
    "boys",
    "total",
    "number",
    "qualification",
    "government",
    "stream",
    "cwsn",
    "higher",
    "educational",
    "students",
    "examination",
    "female",
    "year",
    "disability",
    "male",
    "nature",
    "medium",
    "results",
    "uttar",
    "private",
    "response",
    "rural",
    "gender",
    "current",
    "elementary",
    "madhya",
    "single",
    "appeared",
    "passed",
    "classrooms",
    "regular",
    "bihar",
    "aided",
    "maharashtra",
    "toilet",
    "instruction",
    "repeaters",
    "karnataka",
    "west",
    "condition",
    "rajasthan",
    "gujarat",
    "graduate",
    "odisha",
    "tamil",
    "nadu",
    "received",
    "chhattisgarh",
    "contractual",
    "special",
    "previous",
    "assam",
    "post",
    "madarsas",
    "laboratory",
    "jharkhand",
    "jammu",
    "urban",
    "kashmir",
    "punjab",
    "professional",
    "impairment",
    "haryana",
    "bengal",
    "data",
    "arunachal",
    "classroom",
    "conractual",
    "science",
    "delhi",
    "arts",
    "commerce",
    "vocational",
    "teacher",
    "need",
    "repair",
    "kerala",
    "blind",
    "autism",
    "multiple",
    "playground",
    "water",
    "electricity",
    "ramp",
    "required",
    "established",
    "since",
    "meal",
    "committee",
    "training",
    "children",
    "needs",
    "building",
    "ramps",
    "hostel",
    "result",
    "uttarakhand",
    "nagar",
    "andhra",
    "himachal",
    "service",
    "grant",
    "nagaland",
    "tripura",
    "meghalaya",
    "basic",
    "telangana",
    "reported",
    "professionally",
    "qualified",
    "incentives",
    "none",
    "manipur",
    "census",
    "population",
    "sikkim",
    "mizoram",
    "north",
    "east",
    "south",
    "hills",
    "days",
    "unrecognised",
    "unrecognized",
    "unrcognized",
    "computer",
    "good",
    "minor",
    "major",
    "development",
    "rate",
    "approachable",
    "weather",
    "road",
    "facility",
    "boundarywall",
    "drinking",
    "needed",
    "providing",
    "kitchen",
    "shed",
    "provided",
    "prepared",
    "premises",
    "constituted",
    "management",
    "muslim",
    "vision",
    "hearing",
    "speech",
    "locomotor",
    "mental",
    "retardation",
    "learning",
    "cerebral",
    "palsy",
    "phil",
    "doctorate",
    "academic",
    "instructional",
    "library",
    "librarian",
    "boundary",
    "wall",
    "assistant",
    "separate",
    "room",
    "headmaster",
    "internet",
    "conducted",
    "medical",
    "checkup",
    "smdc",
    "rooms",
    "puducherry",
    "villages",
    "clusters",
    "literacy",
    "textbook",
    "uniform",
    "doctoral",
    "diploma",
    "degree",
    "education",
    "daman",
    "islands",
    "garo",
    "blocks",
    "mediums",
    "instructions",
    "chandigarh",
    "dadra",
    "haveli",
    "lakshadweep",
    "siang",
    "statname",
    "districts",
    "state",
    "expended",
    "percentage",
    "level",
    "grants",
    "general",
    "others",
    "khasi",
    "kannada",
    "bangalore",
    "statcd",
    "distcd",
    "sexratio",
    "code",
    "district",
    "name",
    "group",
    "hamirpur",
    "bilaspur",
    "taran",
    "garhwal",
    "pratapgarh",
    "kanpur",
    "balrampur",
    "champaran",
    "purba",
    "aurangabad",
    "kameng",
    "lower",
    "subansiri",
    "dibang",
    "valley",
    "imphal",
    "jaintia",
    "kamrup",
    "dinajpur",
    "twenty",
    "four",
    "parganas",
    "medinipur",
    "singhbhum",
    "raigarh",
    "bijapur",
    "kantha",
    "mumbai",
    "godavari",
    "belgaum",
    "uttara",
    "tumkur",
    "andamans",
    "distname",
    "totpopulat",
    "growthrate",
    "schtot",
    "schtotg",
    "schtotp",
    "schtotm",
    "schtotgr",
    "schtotga",
    "schtotpr",
    "schboytot",
    "schgirtot",
    "enrtot",
    "enrtotg",
    "enrtotp",
    "enrtotm",
    "enrtotgr",
    "enrtotpr",
    "tchtotg",
    "tchtotp",
    "tchtotm",
    "sclstot",
    "stchtot",
    "roadtot",
    "splaytot",
    "sbndrtot",
    "sgtoiltot",
    "sbtoiltot",
    "swattot",
    "seletot",
    "scomptot",
    "sramtot",
    "sramntot",
    "estdtot",
    "mdmtot",
    "kittot",
    "kitstot",
    "smctot",
    "clstot",
    "tchtot",
    "tchftot"
]

# Layer 2: Reference Intent Exemplars
INTENT_EXAMPLES = {
    "medical": [
        "What are the symptoms of type 2 diabetes?",
        "How is hypertension diagnosed?",
        "What is the recommended treatment for high blood pressure?",
        "How does insulin help in controlling blood sugar?",
        "What causes a sore throat?",
        "Is there an annual vaccine for influenza?"
    ],
    "legal": [
        "What are the requirements of a legally binding contract?",
        "Explain patent protection and how to get a patent.",
        "What is the landlord-tenant act for security deposits?",
        "What are landlord responsibilities regarding habitability?",
        "How is intellectual property protected?",
        "What happens if a contract is breached?"
    ]
}

# Pre-compute exemplars embeddings
EXEMPLAR_EMBEDDINGS = {}
for category, queries in INTENT_EXAMPLES.items():
    embeddings = lancedb_client.embed_model.encode(queries, convert_to_numpy=True)
    EXEMPLAR_EMBEDDINGS[category] = embeddings

def cosine_similarity(v1, v2):
    dot_product = np.dot(v1, v2)
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)
    return dot_product / (norm_v1 * norm_v2) if norm_v1 > 0 and norm_v2 > 0 else 0.0

def classify_domain(text: str) -> tuple[str, float]:
    """
    Returns (domain, confidence_score).
    domain can be: 'medical', 'legal', 'mixed_medical_legal', 'out_of_domain'
    """
    text_lower = text.lower()
    
    # 1. Denylist check
    for word in DENYLIST_KEYWORDS:
        if rf"\b{word}\b" in text_lower or word in text_lower:
            return "out_of_domain", 1.0

    # 2. Embedding Similarity calculation
    query_emb = lancedb_client.embed_model.encode(text, convert_to_numpy=True)
    
    max_med = 0.0
    for emb in EXEMPLAR_EMBEDDINGS["medical"]:
        sim = cosine_similarity(query_emb, emb)
        if sim > max_med:
            max_med = sim
            
    max_leg = 0.0
    for emb in EXEMPLAR_EMBEDDINGS["legal"]:
        sim = cosine_similarity(query_emb, emb)
        if sim > max_leg:
            max_leg = sim

    # 3. Keyword presence analysis
    has_med_keyword = any(word in text_lower for word in MEDICAL_KEYWORDS)
    has_leg_keyword = any(word in text_lower for word in LEGAL_KEYWORDS)

    # Apply keyword-boost to similarity scores
    if has_med_keyword:
        max_med = max(max_med, 0.88)
    if has_leg_keyword:
        max_leg = max(max_leg, 0.88)

    # High-strictness threshold (0.85)
    threshold = 0.85
    
    if max_med >= threshold and max_leg >= threshold:
        return "mixed_medical_legal", max(max_med, max_leg)
    elif max_med >= threshold:
        return "medical", max_med
    elif max_leg >= threshold:
        return "legal", max_leg
    else:
        return "out_of_domain", 1.0 - max(max_med, max_leg)
